from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

from realtime_ops import (
    WORK_ORDER_DECISIONS_PATH,
    create_work_order_decision,
    create_work_order_draft,
    predict_field_event,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = PROJECT_ROOT / "data" / "ai4i2020.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
MOCK_SUMMARY_JSON = OUTPUT_DIR / "mock_field_bridge_summary.json"
MOCK_SUMMARY_MD = OUTPUT_DIR / "mock_field_bridge_summary.md"

SENSOR_COLUMNS = [
    "Type",
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Local MQTT/OPC UA style mock bridge for Stage 19 field-event payloads. "
            "This does not connect to real factory equipment."
        )
    )
    parser.add_argument(
        "--protocol",
        choices=["mqtt_mock", "opcua_mock"],
        default="mqtt_mock",
        help="Name of the local mock bridge protocol to record in source_system.",
    )
    parser.add_argument(
        "--csv-path",
        default="",
        help="Optional CSV with AI4I-compatible sensor columns. Defaults to data/ai4i2020.csv.",
    )
    parser.add_argument("--rows", type=int, default=3, help="Number of rows to publish.")
    parser.add_argument(
        "--equipment-prefix",
        default="mock-press",
        help="Equipment id prefix used for generated field events.",
    )
    parser.add_argument(
        "--create-drafts",
        action="store_true",
        help="Create a human-approval work-order draft for every mock event.",
    )
    parser.add_argument(
        "--decision",
        choices=["", "approve", "reject", "needs_review"],
        default="",
        help="Optionally record one operator decision for each generated draft.",
    )
    return parser.parse_args()


def load_sensor_rows(csv_path: str, rows: int) -> pd.DataFrame:
    """Load or sample AI4I-compatible sensor rows for mock bridge publishing."""
    path = Path(csv_path) if csv_path else DATA_PATH
    if not path.exists():
        raise FileNotFoundError(f"Input CSV not found: {path}")

    df = pd.read_csv(path)
    missing = [column for column in SENSOR_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(f"Mock bridge input CSV is missing columns: {missing}")

    selected = df[SENSOR_COLUMNS].copy()
    if len(selected) > rows:
        # Prefer varied rows that are useful for demo, while keeping deterministic output.
        selected = selected.sort_values(["Tool wear [min]", "Torque [Nm]"], ascending=False).head(rows)
    return selected.head(rows).reset_index(drop=True)


def write_summary(events: list[dict], drafts: list[dict], decisions: list[dict], protocol: str) -> None:
    """Save a small mock bridge summary artifact."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "scope": "local mock bridge only; not a real PLC/SCADA connection",
        "protocol": protocol,
        "event_count": len(events),
        "draft_count": len(drafts),
        "decision_count": len(decisions),
        "events": [
            {
                "event_id": event["event_id"],
                "source": event["source"],
                "probability": event["probability"],
                "risk_status": event["risk_status"],
                "equipment_id": event.get("field_event", {}).get("equipment_id", ""),
            }
            for event in events
        ],
        "draft_ids": [draft["draft_id"] for draft in drafts],
        "decision_ids": [decision["decision_id"] for decision in decisions],
        "decisions_csv": str(WORK_ORDER_DECISIONS_PATH),
    }
    MOCK_SUMMARY_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    lines = [
        "# Mock Field Bridge Summary",
        "",
        "This artifact was generated by a local MQTT/OPC UA style mock bridge. It does not prove real PLC/SCADA connectivity.",
        "",
        f"- Protocol: `{protocol}`",
        f"- Events: `{len(events)}`",
        f"- Drafts: `{len(drafts)}`",
        f"- Decisions: `{len(decisions)}`",
        "",
        "| Event ID | Equipment | Probability | Risk | Source |",
        "|---|---|---:|---|---|",
    ]
    for event in events:
        field_event = event.get("field_event", {})
        lines.append(
            f"| `{event['event_id']}` | `{field_event.get('equipment_id', '')}` | "
            f"{event['probability']:.4f} | {event['risk_status']} | `{event['source']}` |"
        )
    lines.extend(
        [
            "",
            "## Guardrail",
            "",
            "Use this as a local connector-contract demonstration. Do not describe it as real PLC/SCADA deployment.",
            "",
        ]
    )
    MOCK_SUMMARY_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    if args.rows <= 0:
        raise ValueError("--rows must be greater than zero.")
    if args.decision and not args.create_drafts:
        raise ValueError("--decision requires --create-drafts.")

    rows = load_sensor_rows(args.csv_path, args.rows)
    start_time = datetime.now().astimezone().replace(microsecond=0)
    events = []
    drafts = []
    decisions = []

    for index, row in rows.iterrows():
        equipment_id = f"{args.equipment_prefix}-{index + 1:02d}"
        event_timestamp = (start_time + timedelta(minutes=int(index))).isoformat()
        event = predict_field_event(
            equipment_id=equipment_id,
            event_timestamp=event_timestamp,
            source_system=args.protocol,
            row=row.to_dict(),
            persist=True,
        )
        events.append(event)

        if args.create_drafts:
            draft = create_work_order_draft(event)
            drafts.append(draft)
            if args.decision:
                decisions.append(
                    create_work_order_decision(
                        draft_id=draft["draft_id"],
                        decision=args.decision,
                        operator_id=f"{args.protocol}_operator",
                        note="Recorded from local mock field bridge.",
                    )
                )

    write_summary(events, drafts, decisions, args.protocol)
    print("Mock field bridge finished successfully.")
    print(f"protocol: {args.protocol}")
    print(f"events: {len(events)}")
    print(f"drafts: {len(drafts)}")
    print(f"decisions: {len(decisions)}")
    print(f"summary_json: {MOCK_SUMMARY_JSON}")
    print(f"summary_md: {MOCK_SUMMARY_MD}")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"Mock field bridge failed: {error}", file=sys.stderr)
        raise
